[build]
  base    = "demo"
  command = "gatsby build"
  publish = "public/"
 
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
  
[[plugins]]
package = "netlify-deployment-hours-plugin"

  [plugins.inputs]
  
  expression = "* * * * *"
  timezone = "America/Toronto"

